# Pipeline for Binding Tools for Swift.
#
# yaml help: https://aka.ms/yaml

trigger:
- '*'

jobs:
- job: ContinuousIntegration
  timeoutInMinutes: 720 # 12 hours (but 6 is max on hosted agents)
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - script: |
      set +e # we don't care about errors here
      set -x
      pwd
      env | sort
      ls -la /Applications
      system_profiler SPHardwareDataType
      curl -s https://support-sp.apple.com/sp/product?cc=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}' | cut -c 9-) | sed 's|.*<configCode>\(.*\)</configCode>.*|\1|'
      sysctl -a | grep cpu
      exit 0 # make sure we don't return an error code if the last command failed
    displayName: 'Environment info'

  - script: |
      set -e
      set -x
      ./jenkins/provision-deps.sh
    displayName: 'Provision dependencies'

  - script: |
      set -e
      set -x
      ./jenkins/build-swift.sh --publish
      mkdir -p ../toolchain
      if test -f Pack-Man/SwiftToolchain-*.zip; then
        cp -c Pack-Man/SwiftToolchain-*.zip ../toolchain
      fi
    displayName: 'Build Swift'

  # This will upload the updated toolchain zip (if any) to Azure Devops
  # Then there's a Release pipeline which will publish the toolchain zip to Azure Blob Storage.
  - task: PublishBuildArtifacts@1
    displayName: 'Upload Swift Toolchain'
    inputs:
      PathtoPublish: '../toolchain'
      ArtifactName: 'toolchain'
      publishLocation: 'Container'

  - script: |
      set -e
      set -x
      ./jenkins/build.sh
    displayName: 'Build'

  - script: |
      set -e
      set -x
      ./jenkins/build-package.sh
      ls -la ../package || true
    displayName: 'Package'

  # This will upload the packages to Azure Devops
  # Then there's a Release pipeline which will publish the packages to Azure Blob Storage.
  - task: PublishBuildArtifacts@1
    displayName: 'Upload Packages'
    inputs:
      PathtoPublish: '../package'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - script: |
      set -e
      set -x
      ./jenkins/run-tests.sh
    displayName: 'Run tests'
